### ISSUE TITLE
Add `mapPreset` and `civPreset` query parameters to enforce correct draft types

### ISSUE THREAD

**Issue by Kjir** [ZetaTwo/aoe2replaypacker#7]
Currently the map draft and civ draft links are optional and will only display a warning if they don't match the TCC presets. To both ensure players do fill out those fields and still allow any tournament to use this tool, I suggest to add two query parameters, `mapPreset=abcDEF` and `civPreset=abcDEF` which, when set, determine which preset is expected for the map and civ draft. When these parameters are set, the drafts become required fields, if left out the default remains as it is right now.

**Comment by ZetaTwo** [comment]
Added `civpresets` and `mappresets` as query parameters which both take a comma-separated list of acceptable draft presets. If provided, the "(optional)" text of the draft section will disappear.

Currently you can still skip entering but I will update it so that drafts needs to be provided and display an appropriate error message if they are not.

**Comment by ZetaTwo** [comment]
I settled for showing a warning if the draft is not provided. I'm not yet comfortable with enforcing this. Will close this issue as done for now.
